import { lazy, type ComponentType, type LazyExoticComponent } from 'react'

/** Nevesített exportból lusta route-komponens; minden oldal külön chunkba kerül. */
function page<K extends string>(
  load: () => Promise<Record<K, ComponentType>>,
  name: K,
): LazyExoticComponent<ComponentType> {
  return lazy(async () => ({ default: (await load())[name] }))
}

export const Home = page(() => import('../features/home/Home'), 'Home')
export const TaskList = page(() => import('../features/catalog/pages/TaskList'), 'TaskList')
export const TaskSolve = page(() => import('../features/workspace/pages/TaskSolve'), 'TaskSolve')
export const Register = page(() => import('../features/auth/pages/Register'), 'Register')
export const RegisterDone = page(() => import('../features/auth/pages/RegisterDone'), 'RegisterDone')
export const Login = page(() => import('../features/auth/pages/Login'), 'Login')
export const VerifyEmail = page(() => import('../features/auth/pages/VerifyEmail'), 'VerifyEmail')
export const ForgotPassword = page(() => import('../features/auth/pages/ForgotPassword'), 'ForgotPassword')
export const ResetPassword = page(() => import('../features/auth/pages/ResetPassword'), 'ResetPassword')
export const Subscribe = page(() => import('../features/billing/pages/Subscribe'), 'Subscribe')
export const PaymentReturn = page(() => import('../features/billing/pages/PaymentReturn'), 'PaymentReturn')
export const AccountSubscription = page(() => import('../features/billing/pages/AccountSubscription'), 'AccountSubscription')
export const AccountPayments = page(() => import('../features/billing/pages/AccountPayments'), 'AccountPayments')
export const AccountBilling = page(() => import('../features/billing/pages/AccountBilling'), 'AccountBilling')
export const ProgressDashboard = page(() => import('../features/progress/pages/ProgressDashboard'), 'ProgressDashboard')
export const AdminCatalog = page(() => import('../features/admin/catalog/pages/AdminCatalog'), 'AdminCatalog')
export const AdminTrack = page(() => import('../features/admin/catalog/pages/AdminTrack'), 'AdminTrack')
export const AdminModule = page(() => import('../features/admin/catalog/pages/AdminModule'), 'AdminModule')
export const AdminLesson = page(() => import('../features/admin/catalog/pages/AdminLesson'), 'AdminLesson')
export const AdminExercise = page(() => import('../features/admin/catalog/pages/AdminExercise'), 'AdminExercise')
export const AdminNewExercise = page(() => import('../features/admin/catalog/pages/AdminExercise'), 'AdminNewExercise')
export const AdminUsers = page(() => import('../features/admin/users/pages/AdminUsers'), 'AdminUsers')
export const AdminUserDetail = page(() => import('../features/admin/users/pages/AdminUserDetail'), 'AdminUserDetail')
export const AdminInvoices = page(() => import('../features/admin/invoices/pages/AdminInvoices'), 'AdminInvoices')
export const LearningPath = page(() => import('../features/learning/pages/LearningPath'), 'LearningPath')
export const TrackPage = page(() => import('../features/learning/pages/TrackPage'), 'TrackPage')
export const LessonPage = page(() => import('../features/learning/pages/LessonPage'), 'LessonPage')
export const Pricing = page(() => import('../features/marketing/pages/Pricing'), 'Pricing')
export const PrivacyPolicy = page(() => import('../features/legal/LegalPage'), 'PrivacyPolicy')
export const TermsOfService = page(() => import('../features/legal/LegalPage'), 'TermsOfService')
export const Onboarding = page(() => import('../features/onboarding/pages/Onboarding'), 'Onboarding')
export const Oral = page(() => import('../features/oral/pages/Oral'), 'Oral')
export const OralTopic = page(() => import('../features/oral/pages/OralTopic'), 'OralTopic')
export const AccountProfile = page(() => import('../features/account/pages/AccountProfile'), 'AccountProfile')
export const ExamList = page(() => import('../features/exams/pages/ExamList'), 'ExamList')
export const ExamStart = page(() => import('../features/exams/pages/ExamStart'), 'ExamStart')
export const ExamRunner = page(() => import('../features/exams/pages/ExamRunner'), 'ExamRunner')
export const ExamResult = page(() => import('../features/exams/pages/ExamResult'), 'ExamResult')
export const SubmissionPage = page(() => import('../features/filetasks/pages/SubmissionPage'), 'SubmissionPage')
export const AdminOverview = page(() => import('../features/admin/overview/pages/AdminOverview'), 'AdminOverview')
export const AdminExams = page(() => import('../features/admin/exams/pages/AdminExams'), 'AdminExams')
export const AdminExam = page(() => import('../features/admin/exams/pages/AdminExam'), 'AdminExam')
